export enum PlaceType {
    HEALTHCARE = 'HEALTHCARE',
    RESTAURANT = 'RESTAURANT',
    PHARMACY = 'PHARMACY',
    SUPERMARKET = 'SUPERMARKET',
    SHOPPING_CENTER = 'SHOPPING_CENTER',
    BANK = 'BANK',
    UNIVERSITY = 'UNIVERSITY',
    SCHOOL = 'SCHOOL',
    HOTEL = 'HOTEL',
    PUBLIC_SERVICE = 'PUBLIC_SERVICE',
    OTHER = 'OTHER'
}